//HintName: GeneratedAITools.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>Gets first</summary>
public class IFirstServiceGetFirstAsyncAITool : global::Microsoft.Extensions.AI.AIFunction
{
    private readonly global::TestNamespace.IFirstService _service;

    public IFirstServiceGetFirstAsyncAITool(global::TestNamespace.IFirstService service)
    {
        _service = service;
    }

    public override string Name => "IFirstServiceGetFirstAsync";
    public override string Description => "Gets first";


    protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
        global::System.Threading.CancellationToken cancellationToken)
    {
        return await _service.GetFirstAsync();
    }
}

/// <summary>Gets second</summary>
public class ISecondServiceGetSecondAsyncAITool : global::Microsoft.Extensions.AI.AIFunction
{
    private readonly global::TestNamespace.ISecondService _service;

    public ISecondServiceGetSecondAsyncAITool(global::TestNamespace.ISecondService service)
    {
        _service = service;
    }

    public override string Name => "ISecondServiceGetSecondAsync";
    public override string Description => "Gets second";


    protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
        global::System.Threading.CancellationToken cancellationToken)
    {
        return await _service.GetSecondAsync();
    }
}

public static class __GeneratedAIToolRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedAITools(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddTransient<global::Microsoft.Extensions.AI.AITool, global::TestAssembly.IFirstServiceGetFirstAsyncAITool>();
        services.AddTransient<global::Microsoft.Extensions.AI.AITool, global::TestAssembly.ISecondServiceGetSecondAsyncAITool>();
        return services;
    }
}
