//HintName: GeneratedAITools.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>Gets data</summary>
public class IMyServiceGetDataAsyncAITool : global::Microsoft.Extensions.AI.AIFunction
{
    private readonly global::TestNamespace.IMyService _service;

    [global::System.ComponentModel.Description("The query")]
    public string Query { get; set; } = default!;

    public IMyServiceGetDataAsyncAITool(global::TestNamespace.IMyService service)
    {
        _service = service;
    }

    public override string Name => "IMyServiceGetDataAsync";
    public override string Description => "Gets data";

    public override global::System.Text.Json.JsonElement JsonSchema { get; } =
        global::System.Text.Json.JsonDocument.Parse("""
        {
            "type": "object",
            "properties": {
                "query": { "type": "string", "description": "The query" }
            }
            ,"required": ["query"]
        }
        """).RootElement.Clone();

    protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
        global::System.Threading.CancellationToken cancellationToken)
    {
        var __json = global::System.Text.Json.JsonSerializer.SerializeToElement(arguments);

        this.Query = __json.GetProperty("query").GetString()!;

        return await _service.GetDataAsync(this.Query, cancellationToken);
    }
}

public static class __GeneratedAIToolRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedAITools(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddTransient<global::Microsoft.Extensions.AI.AITool, global::TestAssembly.IMyServiceGetDataAsyncAITool>();
        return services;
    }
}
