//HintName: GeneratedAITools.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>Sets the amount</summary>
public class IMyServiceSetAmountAsyncAITool : global::Microsoft.Extensions.AI.AIFunction
{
    private readonly global::TestNamespace.IMyService _service;

    [global::System.ComponentModel.Description("The amount")]
    public double Amount { get; set; } = default!;

    public IMyServiceSetAmountAsyncAITool(global::TestNamespace.IMyService service)
    {
        _service = service;
    }

    public override string Name => "IMyServiceSetAmountAsync";
    public override string Description => "Sets the amount";

    public override global::System.Text.Json.JsonElement JsonSchema { get; } =
        global::System.Text.Json.JsonDocument.Parse("""
        {
            "type": "object",
            "properties": {
                "amount": { "type": "number", "description": "The amount" }
            }
            ,"required": ["amount"]
        }
        """).RootElement.Clone();

    protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
        global::System.Threading.CancellationToken cancellationToken)
    {
        var __json = global::System.Text.Json.JsonSerializer.SerializeToElement(arguments);

        this.Amount = __json.GetProperty("amount").GetDouble();

        await _service.SetAmountAsync(this.Amount);
        return null;
    }
}

public static class __GeneratedAIToolRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedAITools(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddTransient<global::Microsoft.Extensions.AI.AITool, global::TestAssembly.IMyServiceSetAmountAsyncAITool>();
        return services;
    }
}
