//HintName: GeneratedAITools.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>Does something</summary>
public class IMyServiceDoSomethingAITool : global::Microsoft.Extensions.AI.AIFunction
{
    private readonly global::TestNamespace.IMyService _service;

    public IMyServiceDoSomethingAITool(global::TestNamespace.IMyService service)
    {
        _service = service;
    }

    public override string Name => "IMyServiceDoSomething";
    public override string Description => "Does something";


    protected override global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
        global::System.Threading.CancellationToken cancellationToken)
    {
        _service.DoSomething();
        return new global::System.Threading.Tasks.ValueTask<object?>((object?)null);
    }
}

/// <summary>Does something async</summary>
public class IMyServiceDoSomethingAsyncAITool : global::Microsoft.Extensions.AI.AIFunction
{
    private readonly global::TestNamespace.IMyService _service;

    public IMyServiceDoSomethingAsyncAITool(global::TestNamespace.IMyService service)
    {
        _service = service;
    }

    public override string Name => "IMyServiceDoSomethingAsync";
    public override string Description => "Does something async";


    protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
        global::System.Threading.CancellationToken cancellationToken)
    {
        await _service.DoSomethingAsync();
        return null;
    }
}

/// <summary>Gets something</summary>
public class IMyServiceGetSomethingByNameAsyncAITool : global::Microsoft.Extensions.AI.AIFunction
{
    private readonly global::TestNamespace.IMyService _service;

    [global::System.ComponentModel.Description("The name")]
    public string Name { get; set; } = default!;

    public IMyServiceGetSomethingByNameAsyncAITool(global::TestNamespace.IMyService service)
    {
        _service = service;
    }

    public override string Name => "IMyServiceGetSomethingByNameAsync";
    public override string Description => "Gets something";

    public override global::System.Text.Json.JsonElement JsonSchema { get; } =
        global::System.Text.Json.JsonDocument.Parse("""
        {
            "type": "object",
            "properties": {
                "name": { "type": "string", "description": "The name" }
            }
            ,"required": ["name"]
        }
        """).RootElement.Clone();

    protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
        global::System.Threading.CancellationToken cancellationToken)
    {
        var __json = global::System.Text.Json.JsonSerializer.SerializeToElement(arguments);

        this.Name = __json.GetProperty("name").GetString()!;

        return await _service.GetSomethingByNameAsync(this.Name);
    }
}

public static class __GeneratedAIToolRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedAITools(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddTransient<global::Microsoft.Extensions.AI.AITool, global::TestAssembly.IMyServiceDoSomethingAITool>();
        services.AddTransient<global::Microsoft.Extensions.AI.AITool, global::TestAssembly.IMyServiceDoSomethingAsyncAITool>();
        services.AddTransient<global::Microsoft.Extensions.AI.AITool, global::TestAssembly.IMyServiceGetSomethingByNameAsyncAITool>();
        return services;
    }
}
