//HintName: GeneratedAITools.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>Sets timeout</summary>
public class IMyServiceSetTimeoutAsyncAITool : global::Microsoft.Extensions.AI.AIFunction
{
    private readonly global::TestNamespace.IMyService _service;

    [global::System.ComponentModel.Description("The duration")]
    public global::System.TimeSpan Duration { get; set; } = default!;

    public IMyServiceSetTimeoutAsyncAITool(global::TestNamespace.IMyService service)
    {
        _service = service;
    }

    public override string Name => "IMyServiceSetTimeoutAsync";
    public override string Description => "Sets timeout";

    public override global::System.Text.Json.JsonElement JsonSchema { get; } =
        global::System.Text.Json.JsonDocument.Parse("""
        {
            "type": "object",
            "properties": {
                "duration": { "type": "string", "description": "The duration" }
            }
            ,"required": ["duration"]
        }
        """).RootElement.Clone();

    protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
        global::System.Threading.CancellationToken cancellationToken)
    {
        var __json = global::System.Text.Json.JsonSerializer.SerializeToElement(arguments);

        this.Duration = global::System.TimeSpan.Parse(__json.GetProperty("duration").GetString()!);

        await _service.SetTimeoutAsync(this.Duration);
        return null;
    }
}

public static class __GeneratedAIToolRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedAITools(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddTransient<global::Microsoft.Extensions.AI.AITool, global::TestAssembly.IMyServiceSetTimeoutAsyncAITool>();
        return services;
    }
}
