//HintName: GeneratedAITools.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>Creates an item</summary>
public class IMyServiceCreateAsyncAITool : global::Microsoft.Extensions.AI.AIFunction
{
    private readonly global::TestNamespace.IMyService _service;

    [global::System.ComponentModel.Description("The name")]
    public string Name { get; set; } = default!;

    [global::System.ComponentModel.Description("The count")]
    public int Count { get; set; } = default!;

    [global::System.ComponentModel.Description("Whether enabled")]
    public bool Enabled { get; set; } = default!;

    public IMyServiceCreateAsyncAITool(global::TestNamespace.IMyService service)
    {
        _service = service;
    }

    public override string Name => "IMyServiceCreateAsync";
    public override string Description => "Creates an item";

    public override global::System.Text.Json.JsonElement JsonSchema { get; } =
        global::System.Text.Json.JsonDocument.Parse("""
        {
            "type": "object",
            "properties": {
                "name": { "type": "string", "description": "The name" },
                "count": { "type": "integer", "description": "The count" },
                "enabled": { "type": "boolean", "description": "Whether enabled" }
            }
            ,"required": ["name", "count", "enabled"]
        }
        """).RootElement.Clone();

    protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
        global::System.Threading.CancellationToken cancellationToken)
    {
        var __json = global::System.Text.Json.JsonSerializer.SerializeToElement(arguments);

        this.Name = __json.GetProperty("name").GetString()!;
        this.Count = __json.GetProperty("count").GetInt32();
        this.Enabled = __json.GetProperty("enabled").GetBoolean();

        return await _service.CreateAsync(this.Name, this.Count, this.Enabled);
    }
}

public static class __GeneratedAIToolRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedAITools(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddTransient<global::Microsoft.Extensions.AI.AITool, global::TestAssembly.IMyServiceCreateAsyncAITool>();
        return services;
    }
}
