//HintName: TestNamespace.AppSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class AppSettings
{
    public partial long Counter
    {
        get => global::Shiny.StoreExtensions.Get<long>(global::Shiny.Stores.Default, "Counter", (long)(0));
        set
        {
            var __old = global::Shiny.Stores.Default.Get<long>("Counter")!;
            if (global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(__old, value))
                return;

            global::Shiny.Stores.Default.Set("Counter", value);
            this.OnCounterChanged(__old, value);
        }
    }
    partial void OnCounterChanged(long oldValue, long newValue);

    public static class Binds
    {
        public static readonly global::Shiny.BindInfo Counter = new("Counter", typeof(long), null, "Counter");

        public static readonly global::Shiny.BindInfo[] All = { Counter };
    }
}
