//HintName: TestNamespace.SecureSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class SecureSettings
{
    public partial string Token
    {
        get => global::Shiny.Stores.Secure.Get<string>("Token")!;
        set => global::Shiny.Stores.Secure.Set("Token", value);
    }
}
