//HintName: TestNamespace.AppSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class AppSettings
{
    public partial string Token
    {
        get => global::Shiny.StoreExtensions.Get<string>(global::Shiny.Stores.Secure, "auth-token", "anonymous");
        set
        {
            var __old = global::Shiny.Stores.Secure.Get<string>("auth-token")!;
            if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__old, value))
                return;

            global::Shiny.Stores.Secure.Set("auth-token", value);
            this.OnTokenChanged(__old, value);
        }
    }
    partial void OnTokenChanged(string oldValue, string newValue);

    public static class Binds
    {
        public static readonly global::Shiny.BindInfo Token = new("Token", typeof(string), "secure", "auth-token");

        public static readonly global::Shiny.BindInfo[] All = { Token };
    }
}
