//HintName: TestNamespace.AppSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class AppSettings
{
    public partial bool IsEnabled
    {
        get => global::Shiny.StoreExtensions.Get<bool>(global::Shiny.Stores.Default, "IsEnabled", true);
        set
        {
            var __old = global::Shiny.Stores.Default.Get<bool>("IsEnabled")!;
            if (global::System.Collections.Generic.EqualityComparer<bool>.Default.Equals(__old, value))
                return;

            global::Shiny.Stores.Default.Set("IsEnabled", value);
            this.OnIsEnabledChanged(__old, value);
        }
    }
    partial void OnIsEnabledChanged(bool oldValue, bool newValue);

    public static class Binds
    {
        public static readonly global::Shiny.BindInfo IsEnabled = new("IsEnabled", typeof(bool), null, "IsEnabled");

        public static readonly global::Shiny.BindInfo[] All = { IsEnabled };
    }
}
