//HintName: TestNamespace.AppSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class AppSettings
{
    public partial string Theme
    {
        get => global::Shiny.Stores.Default.Get<string>("Theme")!;
        set => global::Shiny.Stores.Default.Set("Theme", value);
    }
}
