//HintName: TestNamespace.AppSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class AppSettings
{
    public partial string Theme
    {
        get => global::Shiny.Stores.Default.Get<string>("Theme")!;
        set
        {
            var __old = global::Shiny.Stores.Default.Get<string>("Theme")!;
            if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__old, value))
                return;

            global::Shiny.Stores.Default.Set("Theme", value);
            this.OnThemeChanged(__old, value);
            this.OnPropertyChanged(nameof(Theme));
        }
    }
    partial void OnThemeChanged(string oldValue, string newValue);

    public static class Binds
    {
        public static readonly global::Shiny.BindInfo Theme = new("Theme", typeof(string), null, "Theme");

        public static readonly global::Shiny.BindInfo[] All = { Theme };
    }
}
