//HintName: TestNamespace.AppSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class AppSettings
{
    public partial int Counter
    {
        get => global::Shiny.Stores.Default.Get<int>("custom-key")!;
        set => global::Shiny.Stores.Default.Set("custom-key", value);
    }
}
