//HintName: TestNamespace.AppSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class AppSettings
{
    public partial int RetryCount
    {
        get => global::Shiny.StoreExtensions.Get<int>(global::Shiny.Stores.Default, "RetryCount", 5);
        set
        {
            var __old = global::Shiny.StoreExtensions.Get<int>(global::Shiny.Stores.Default, "RetryCount", 5);
            if (global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__old, value))
                return;

            global::Shiny.Stores.Default.Set("RetryCount", value);
            this.OnRetryCountChanged(__old, value);
        }
    }
    partial void OnRetryCountChanged(int oldValue, int newValue);

    public static class Binds
    {
        public static readonly global::Shiny.BindInfo RetryCount = new("RetryCount", typeof(int), null, "RetryCount");

        public static readonly global::Shiny.BindInfo[] All = { RetryCount };
    }
}
