//HintName: TestNamespace.AppSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class AppSettings : global::System.ComponentModel.INotifyPropertyChanged
{
    public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

    public partial string Theme
    {
        get => global::Shiny.Stores.Default.Get<string>("Theme")!;
        set
        {
            var __old = global::Shiny.Stores.Default.Get<string>("Theme")!;
            if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__old, value))
                return;

            global::Shiny.Stores.Default.Set("Theme", value);
            this.OnThemeChanged(__old, value);
            this.PropertyChanged?.Invoke(this, __BindEvents.Theme);
        }
    }
    partial void OnThemeChanged(string oldValue, string newValue);

    public partial string Token
    {
        get => global::Shiny.Stores.Secure.Get<string>("Token")!;
        set
        {
            var __old = global::Shiny.Stores.Secure.Get<string>("Token")!;
            if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__old, value))
                return;

            global::Shiny.Stores.Secure.Set("Token", value);
            this.OnTokenChanged(__old, value);
            this.PropertyChanged?.Invoke(this, __BindEvents.Token);
        }
    }
    partial void OnTokenChanged(string oldValue, string newValue);

    private static class __BindEvents
    {
        public static readonly global::System.ComponentModel.PropertyChangedEventArgs Theme = new("Theme");
        public static readonly global::System.ComponentModel.PropertyChangedEventArgs Token = new("Token");
    }

    public static class Binds
    {
        public static readonly global::Shiny.BindInfo Theme = new("Theme", typeof(string), null, "Theme");
        public static readonly global::Shiny.BindInfo Token = new("Token", typeof(string), "secure", "Token");

        public static readonly global::Shiny.BindInfo[] All = { Theme, Token };
    }
}
