//HintName: TestNamespace.AppSettings.Binds.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace;

partial class AppSettings
{
    public partial global::TestNamespace.Mode Setting
    {
        get => global::Shiny.StoreExtensions.Get<global::TestNamespace.Mode>(global::Shiny.Stores.Default, "Setting", (global::TestNamespace.Mode)2);
        set
        {
            var __old = global::Shiny.StoreExtensions.Get<global::TestNamespace.Mode>(global::Shiny.Stores.Default, "Setting", (global::TestNamespace.Mode)2);
            if (global::System.Collections.Generic.EqualityComparer<global::TestNamespace.Mode>.Default.Equals(__old, value))
                return;

            global::Shiny.Stores.Default.Set("Setting", value);
            this.OnSettingChanged(__old, value);
        }
    }
    partial void OnSettingChanged(global::TestNamespace.Mode oldValue, global::TestNamespace.Mode newValue);

    public static class Binds
    {
        public static readonly global::Shiny.BindInfo Setting = new("Setting", typeof(global::TestNamespace.Mode), null, "Setting");

        public static readonly global::Shiny.BindInfo[] All = { Setting };
    }
}
