//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::System.Linq;
using global::Microsoft.Extensions.DependencyInjection;
using global::Microsoft.Extensions.DependencyInjection.Extensions;

namespace TestAssembly;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        params string[] categories
    )
    {
        services.AddSingleton<global::TestNamespace.MyService>(sp => new global::TestNamespace.MyService());
        services.AddSingleton<global::TestNamespace.IFoo>(sp => sp.GetRequiredService<global::TestNamespace.MyService>());
        services.AddSingleton<global::TestNamespace.IBar>(sp => sp.GetRequiredService<global::TestNamespace.MyService>());

        return services;
    }
}
