//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::System.Linq;
using global::Microsoft.Extensions.DependencyInjection;
using global::Microsoft.Extensions.DependencyInjection.Extensions;


internal static class __ShinyServicesModule
{
    public static void Run()
    {
        global::Shiny.Extensions.DependencyInjection.Internals.ServiceRegistry.RegisterCallback((services, categories) => {
            services.AddSingleton<global::TestNamespace.IService1, global::TestNamespace.SingletonService>();
            services.AddScoped<global::TestNamespace.IService2, global::TestNamespace.ScopedService>();
            services.AddTransient<global::TestNamespace.IService3, global::TestNamespace.TransientService>();
            services.AddSingleton<global::TestNamespace.AsSelfService>();
        });
    }
}
