//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        string? category = null
    )
    {
        services.AddSingleton<global::TestNamespace.IService1, global::TestNamespace.NormalService>();
        if (category?.Equals("CategoryX", global::System.StringComparison.OrdinalIgnoreCase) == true)
        {
            services.AddTransient<global::TestNamespace.IService2, global::TestNamespace.CategorizedService>();
        }
        services.AddKeyedScoped<global::TestNamespace.IService1, global::TestNamespace.KeyedNormalService>("KeyedNormal");
        if (category?.Equals("CategoryY", global::System.StringComparison.OrdinalIgnoreCase) == true)
        {
            services.AddKeyedScoped<global::TestNamespace.IService2, global::TestNamespace.KeyedCategorizedService>("KeyedCategorized");
        }
        if (category?.Equals("GenericCategory", global::System.StringComparison.OrdinalIgnoreCase) == true)
        {
            services.AddSingleton(typeof(global::TestNamespace.IGenericService<>), typeof(global::TestNamespace.GenericCategorizedService<>));
        }
        services.AddTransient(typeof(global::TestNamespace.IGenericService<>), typeof(global::TestNamespace.GenericNormalService<>));

        return services;
    }
}
