//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        string? category = null
    )
    {
        services.AddSingleton<global::TestNamespace.IService1, global::TestNamespace.ClassService>();
        services.AddTransient<global::TestNamespace.IService2, global::TestNamespace.RecordService>();
        services.AddKeyedScoped<global::TestNamespace.IService1, global::TestNamespace.KeyedRecordService>("MixedKey");

        return services;
    }
}
