//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::System.Linq;
using global::Microsoft.Extensions.DependencyInjection;
using global::Microsoft.Extensions.DependencyInjection.Extensions;

namespace TestAssembly;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        params string[] categories
    )
    {
        services.AddSingleton<global::TestNamespace.IService1, global::TestNamespace.SingletonService>();
        services.AddScoped<global::TestNamespace.IService2, global::TestNamespace.ScopedService>();
        services.AddTransient<global::TestNamespace.IService3, global::TestNamespace.TransientService>();
        services.AddSingleton<global::TestNamespace.AsSelfService>();

        return services;
    }
}
