//HintName: GeneratedRegistrations_Sample.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;
using global::Shiny.Extensions.DependencyInjection;

namespace Sample
{
    public static class __GeneratedRegistrations
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
        )
        {
            services.AddSingleton<ImplementationOnly>();
            services.AddKeyedTransient<KeyedImplementationOnly>("ImplOnly");
            services.AddSingleton<Sample.IStandardInterface, StandardImplementation>();
            services.AddKeyedScoped<Sample.IStandardInterface, KeyedStandardImplementation>("Standard");
            services.AddSingletonAsImplementedInterfaces<MultipleImplementation>();
            services.AddScopedAsImplementedInterfaces<ScopedMultipleImplementation>();

            return services;
        }
    }
}
