//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::System.Linq;
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        params string[] categories
    )
    {
        if (categories?.Any(x => x.Equals("CategoryA", global::System.StringComparison.OrdinalIgnoreCase)) == true)
        {
            services.AddSingleton<global::TestNamespace.IService1, global::TestNamespace.ServiceA>();
        }
        if (categories?.Any(x => x.Equals("CategoryB", global::System.StringComparison.OrdinalIgnoreCase)) == true)
        {
            services.AddTransient<global::TestNamespace.IService2, global::TestNamespace.ServiceB>();
        }
        services.AddScoped<global::TestNamespace.IService3, global::TestNamespace.ServiceC>();
        if (categories?.Any(x => x.Equals("CategoryA", global::System.StringComparison.OrdinalIgnoreCase)) == true)
        {
            services.AddKeyedSingleton<global::TestNamespace.IService1, global::TestNamespace.KeyedServiceA>("KeyedService");
        }

        return services;
    }
}
