//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        string? category = null
    )
    {
        if (category?.Equals("CategoryA", global::System.StringComparison.OrdinalIgnoreCase) == true)
        {
            services.AddKeyedScoped<global::TestNamespace.IMyService, global::TestNamespace.MyKeyedService>("MyKey");
        }

        return services;
    }
}
