//HintName: GeneratedRegistrations_TestNamespace.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;
using global::Shiny.Extensions.DependencyInjection;

namespace TestNamespace
{
    public static class __GeneratedRegistrations
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
        )
        {
            services.AddSingleton<TestNamespace.IService1, Service1>();
            services.AddKeyedTransient<KeyedService1>("Key1");
            services.AddScopedAsImplementedInterfaces<Service2>();

            return services;
        }
    }
}
