//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::System.Linq;
using global::Microsoft.Extensions.DependencyInjection;

namespace CustomExtensions;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddCategorizedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        params string[] categories
    )
    {
        if (categories?.Any(x => x.Equals("SpecialCategory", global::System.StringComparison.OrdinalIgnoreCase)) == true)
        {
            services.AddSingleton<global::TestNamespace.IMyService, global::TestNamespace.SpecialService>();
        }
        services.AddTransient<global::TestNamespace.RegularService>();

        return services;
    }
}
