//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::System.Linq;
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        params string[] categories
    )
    {
        services.AddSingleton<global::TestNamespace.IService1, global::TestNamespace.NormalService>();
        if (categories?.Any(x => x.Equals("CategoryX", global::System.StringComparison.OrdinalIgnoreCase)) == true)
        {
            services.AddTransient<global::TestNamespace.IService2, global::TestNamespace.CategorizedService>();
        }
        services.AddKeyedScoped<global::TestNamespace.IService1, global::TestNamespace.KeyedNormalService>("KeyedNormal");
        if (categories?.Any(x => x.Equals("CategoryY", global::System.StringComparison.OrdinalIgnoreCase)) == true)
        {
            services.AddKeyedScoped<global::TestNamespace.IService2, global::TestNamespace.KeyedCategorizedService>("KeyedCategorized");
        }
        if (categories?.Any(x => x.Equals("GenericCategory", global::System.StringComparison.OrdinalIgnoreCase)) == true)
        {
            services.AddSingleton(typeof(global::TestNamespace.IGenericService<>), typeof(global::TestNamespace.GenericCategorizedService<>));
        }
        services.AddTransient(typeof(global::TestNamespace.IGenericService<>), typeof(global::TestNamespace.GenericNormalService<>));

        return services;
    }
}
