//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests
{
    public static class __GeneratedRegistrations
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
        )
        {
            services.AddSingleton(typeof(global::TestNamespace.StandaloneGeneric<,>));
            services.AddKeyedTransient(typeof(global::TestNamespace.KeyedStandaloneGeneric<,,>), "multi");

            return services;
        }
    }
}
