//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests;

internal static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
    )
    {
        services.AddSingleton<global::TestNamespace.IMyService, global::TestNamespace.MyService>();
        services.AddTransient<global::TestNamespace.AnotherService>();

        return services;
    }
}
