//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::System.Linq;
using global::Microsoft.Extensions.DependencyInjection;
using global::Microsoft.Extensions.DependencyInjection.Extensions;

namespace Tests;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        params string[] categories
    )
    {
        services.AddTransient(typeof(global::TestNamespace.ISingleGeneric<>), typeof(global::TestNamespace.MultiArityService<,,>));
        services.AddTransient(typeof(global::TestNamespace.IDualGeneric<,>), typeof(global::TestNamespace.MultiArityService<,,>));
        services.AddTransient(typeof(global::TestNamespace.ITripleGeneric<,,>), typeof(global::TestNamespace.MultiArityService<,,>));

        return services;
    }
}
