//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;
using global::Shiny.Extensions.DependencyInjection;

namespace Tests
{
    public static class __GeneratedRegistrations
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
        )
        {
            services.AddTransient(typeof(global::TestNamespace.IRepository<>), typeof(global::TestNamespace.GenericService<>));
            services.AddTransient(typeof(global::TestNamespace.IGenericService<>), typeof(global::TestNamespace.GenericService<>));

            return services;
        }
    }
}
