//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;
using global::Shiny.Extensions.DependencyInjection;

namespace Tests
{
    public static class __GeneratedRegistrations
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
        )
        {
            services.AddSingleton<global::TestNamespace.IService1, global::TestNamespace.Service1>();
            services.AddKeyedTransient<global::TestNamespace.KeyedService1>("Key1");
            services.AddScopedAsImplementedInterfaces<global::TestNamespace.Service2>();

            return services;
        }
    }
}
