//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
    )
    {
        services.AddSingleton(typeof(global::TestNamespace.IRepository<>), typeof(global::TestNamespace.SingleGeneric<>));
        services.AddScoped(typeof(global::TestNamespace.IConverter<,>), typeof(global::TestNamespace.DualGeneric<,>));
        services.AddTransient(typeof(global::TestNamespace.IProcessor<,,>), typeof(global::TestNamespace.TripleGeneric<,,>));
        services.AddKeyedScoped(typeof(global::TestNamespace.IConverter<,>), typeof(global::TestNamespace.KeyedDualGeneric<,>), "special");

        return services;
    }
}
