//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::System.Linq;
using global::Microsoft.Extensions.DependencyInjection;
using global::Microsoft.Extensions.DependencyInjection.Extensions;


internal static class __ShinyServicesModule
{
    public static void Run()
    {
        global::Shiny.Extensions.DependencyInjection.Internals.ServiceRegistry.RegisterCallback((services, categories) => {
            services.AddTransient<global::TestNamespace.IMyService, global::TestNamespace.MyTransientService>();
        });
    }
}
