//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests
{
    public static class __GeneratedRegistrations
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
        )
        {
            services.AddScoped(typeof(global::TestNamespace.IRepository<>), typeof(global::TestNamespace.GenericRecordRepository<>));
            services.AddScoped(typeof(global::System.IEquatable<TestNamespace.GenericRecordRepository<>), typeof(global::TestNamespace.GenericRecordRepository<>));

            return services;
        }
    }
}
