//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;

namespace Tests;

public static class __GeneratedRegistrations
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        string? category = null
    )
    {
        services.AddSingleton<global::TestNamespace.IService1, global::TestNamespace.Service1>();
        services.AddKeyedTransient<global::TestNamespace.KeyedService1>("Key1");
        global::Shiny.Extensions.DependencyInjection.ServiceCollectionExtensions.AddScopedAsImplementedInterfaces<global::TestNamespace.Service2>(services);

        return services;
    }
}
