//HintName: GeneratedRegistrations.g.cs
// <auto-generated />
using global::Microsoft.Extensions.DependencyInjection;
using global::Shiny.Extensions.DependencyInjection;

namespace AllServices.Extensions
{
    public static class __GeneratedRegistrations
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAllAssemblyServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services
        )
        {
            services.AddSingleton<FirstService>();
            services.AddTransient<SecondService>();
            services.AddScoped<ThirdNamespace.IThirdService, ThirdService>();

            return services;
        }
    }
}
