//HintName: IInfrastructureModule.g.cs
// <auto-generated />
namespace Shiny;


public interface IInfrastructureModule
{
    void Add(global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder);
    void Use(global::Microsoft.AspNetCore.Builder.WebApplication app);
}
