//HintName: InfrastructureExtensions.g.cs
// <auto-generated />
using global::Microsoft.AspNetCore.Builder;
using global::Microsoft.Extensions.DependencyInjection;


namespace Shiny;


public static class InfrastructureExtensions
{
    public static WebApplicationBuilder AddAllInfrastructure(this WebApplicationBuilder builder)
    {
        var module0 = new global::TestNamespace.CorsModule();
        module0.Add(builder);
        builder.Services.AddTransient<global::Shiny.IInfrastructureModule>(_ => module0);

        return builder;
    }

    public static WebApplicationBuilder AddInfrastructureModules(this WebApplicationBuilder builder, params global::Shiny.IInfrastructureModule[] modules)
    {
        foreach (var module in modules)
        {
            module.Add(builder);
            builder.Services.AddTransient<global::Shiny.IInfrastructureModule>(_ => module);
        }
        return builder;
    }

    public static WebApplication UseInfrastructure(this WebApplication app)
    {
        var modules = app.Services.GetServices<global::Shiny.IInfrastructureModule>();
        foreach (var module in modules)
        {
            module.Use(app);
        }
        return app;
    }
}
