using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Shiny.Extensions.WebHosting.SourceGenerators;


[Generator(LanguageNames.CSharp)]
public class WebHostingSourceGenerator : IIncrementalGenerator
{
    const string WebApplicationBuilderType = "Microsoft.AspNetCore.Builder.WebApplicationBuilder";
    const string WebModuleInterfaceName = "IWebModule";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Detect if this is an ASP.NET Core project
        var isAspNetCore = context.CompilationProvider.Select(
            static (compilation, _) => IsAspNetCoreProject(compilation)
        );

        // Find classes implementing IWebModule
        var moduleTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsModuleCandidate(s),
                transform: static (ctx, _) => GetModuleInfo(ctx)
            )
            .Where(static m => m is not null)
            .Collect();

        var combined = isAspNetCore.Combine(moduleTypes);

        context.RegisterSourceOutput(
            combined,
            static (spc, source) => Execute(source.Left, source.Right!, spc)
        );
    }

    static bool IsAspNetCoreProject(Compilation compilation)
    {
        // Check if WebApplicationBuilder type exists in the compilation
        if (compilation.GetTypeByMetadataName(WebApplicationBuilderType) != null)
            return true;

        // Check referenced assembly names for Microsoft.AspNetCore
        foreach (var assembly in compilation.ReferencedAssemblyNames)
        {
            if (assembly.Name.Equals("Microsoft.AspNetCore", System.StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    static bool IsModuleCandidate(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDecl)
            return false;

        if (classDecl.BaseList == null)
            return false;

        foreach (var baseType in classDecl.BaseList.Types)
        {
            var typeName = baseType.Type.ToString();
            if (typeName == WebModuleInterfaceName ||
                typeName == $"Shiny.{WebModuleInterfaceName}" ||
                typeName == $"global::Shiny.{WebModuleInterfaceName}")
                return true;
        }

        return false;
    }

    static ModuleInfo? GetModuleInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (symbol == null || symbol.IsAbstract || symbol.IsStatic)
            return null;

        return new ModuleInfo
        {
            FullClassName = symbol.ToDisplayString()
        };
    }

    static void Execute(bool isAspNetCore, ImmutableArray<ModuleInfo?> modules, SourceProductionContext context)
    {
        if (!isAspNetCore)
            return;

        var validModules = modules.IsDefaultOrEmpty
            ? new System.Collections.Generic.List<ModuleInfo>()
            : modules
                .Where(m => m != null)
                .Cast<ModuleInfo>()
                .GroupBy(m => m.FullClassName)
                .Select(g => g.First())
                .ToList();

        // Generate the extension methods
        context.AddSource("WebModuleExtensions.g.cs", GenerateExtensions(validModules));
    }

    static string GenerateExtensions(System.Collections.Generic.List<ModuleInfo> modules)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using global::Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("namespace Shiny;");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("public static class WebModuleExtensions");
        sb.AppendLine("{");

        // AddAllWebModules
        sb.AppendLine("    public static WebApplicationBuilder AddAllWebModules(this WebApplicationBuilder builder)");
        sb.AppendLine("    {");

        for (var i = 0; i < modules.Count; i++)
        {
            var module = modules[i];
            sb.AppendLine($"        var module{i} = new global::{module.FullClassName}();");
            sb.AppendLine($"        module{i}.Add(builder);");
            sb.AppendLine($"        builder.Services.AddTransient<global::Shiny.IWebModule>(_ => module{i});");
            sb.AppendLine();
        }

        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // AddWebModules
        sb.AppendLine("    public static WebApplicationBuilder AddWebModules(this WebApplicationBuilder builder, params global::Shiny.IWebModule[] modules)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var module in modules)");
        sb.AppendLine("        {");
        sb.AppendLine("            module.Add(builder);");
        sb.AppendLine("            builder.Services.AddTransient<global::Shiny.IWebModule>(_ => module);");
        sb.AppendLine("        }");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // UseWebModules
        sb.AppendLine("    public static WebApplication UseWebModules(this WebApplication app)");
        sb.AppendLine("    {");
        sb.AppendLine("        var modules = app.Services.GetServices<global::Shiny.IWebModule>();");
        sb.AppendLine("        foreach (var module in modules)");
        sb.AppendLine("        {");
        sb.AppendLine("            module.Use(app);");
        sb.AppendLine("        }");
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }
}

class ModuleInfo
{
    public string FullClassName { get; set; } = string.Empty;
}
