//HintName: TestClassReflector.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
internal class TestClassReflector : global::Shiny.Extensions.Reflector.IReflectorClass
{
    private readonly global::TestNamespace.TestClass _reflectedObject;

    internal TestClassReflector(global::TestNamespace.TestClass reflectedObject)
    {
        _reflectedObject = reflectedObject;
    }

    public object ReflectedObject => _reflectedObject;

    public global::Shiny.Extensions.Reflector.PropertyGeneratedInfo[] Properties => new global::Shiny.Extensions.Reflector.PropertyGeneratedInfo[]
    {
        new global::Shiny.Extensions.Reflector.PropertyGeneratedInfo("Name", typeof(string), true),
        new global::Shiny.Extensions.Reflector.PropertyGeneratedInfo("Age", typeof(int), true)
    };

    public T? GetValue<T>(string key)
    {
        var value = this[key];
        if (value == null)
            return default(T);

        return (T)value;
    }

    public object? this[string key]
    {
        get
        {
            switch (key?.ToLower())
            {
                case "name":
                    return _reflectedObject.Name;
                case "age":
                    return _reflectedObject.Age;
                default:
                    throw new global::System.InvalidOperationException($"Cannot get value for key '{key}' in TestClassReflector");
            }
        }
        set
        {
            switch (key?.ToLower())
            {
                case "name":
                    if (value is not null and not string)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector. Expected a string value.");

                    _reflectedObject.Name = (string)value;
                    break;

                case "age":
                    if (value is not null and not int)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector. Expected a int value.");

                    _reflectedObject.Age = (int)value;
                    break;

                default:
                    throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector");
            }
        }
    }

    public void SetValue<T>(string key, T? value)
    {
        this[key] = value;
    }
}
}
