//HintName: TestClass_ReflectorProperty.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public partial class TestClass : global::Shiny.Extensions.Reflector.IHasReflectorClass
{
     private global::Shiny.Extensions.Reflector.IReflectorClass? _reflector;
    public global::Shiny.Extensions.Reflector.IReflectorClass Reflector => _reflector ??= new TestClassReflector(this);
}
}
