using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Shiny.Extensions.Serialization.SourceGenerators;


/// <summary>
/// Emits two kinds of helpers:
/// <list type="bullet">
/// <item><description>
/// For each user-written <c>JsonSerializerContext</c> annotated with
/// <c>[ShinyJsonContext]</c>, a <c>[ModuleInitializer]</c> that calls
/// <c>Shiny.Json.AddContext(MyContext.Default)</c> — drops the manual
/// <c>services.AddJsonContext(...)</c> boilerplate.
/// </description></item>
/// <item><description>
/// For each element type opted in via <c>[ShinyJsonInclude]</c> (type-level) or
/// <c>[assembly: ShinyJsonInclude(typeof(T))]</c>, an AOT-safe
/// <see cref="System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver"/>
/// providing <c>JsonTypeInfo</c> for <c>List&lt;T&gt;</c>, <c>T[]</c>, <c>IEnumerable&lt;T&gt;</c>,
/// <c>IReadOnlyList&lt;T&gt;</c>, <c>IReadOnlyCollection&lt;T&gt;</c>, <c>IList&lt;T&gt;</c>,
/// <c>ICollection&lt;T&gt;</c>, and <c>IAsyncEnumerable&lt;T&gt;</c>. The element <c>JsonTypeInfo</c>
/// is resolved lazily from the chain, so this composes with any source-generated
/// <c>JsonSerializerContext</c> the user has registered.
/// </description></item>
/// </list>
/// </summary>
[Generator(LanguageNames.CSharp)]
public class ShinyJsonContextGenerator : IIncrementalGenerator
{
    const string IncludeAttributeMetadataName = "Shiny.ShinyJsonIncludeAttribute";
    const string ContextAttributeMetadataName = "Shiny.ShinyJsonContextAttribute";
    const string JsonSerializableAttributeMetadataName = "System.Text.Json.Serialization.JsonSerializableAttribute";

    const string AttributesSource = """
// <auto-generated/>
#nullable enable
namespace Shiny
{
    /// <summary>
    /// Marks a user-declared <see cref="global::System.Text.Json.Serialization.JsonSerializerContext"/>
    /// to be auto-registered with <see cref="global::Shiny.Json"/> via a generated
    /// <c>[ModuleInitializer]</c>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class ShinyJsonContextAttribute : global::System.Attribute { }


    /// <summary>
    /// Opts a type into AOT-safe collection wrapping (<c>List&lt;T&gt;</c>, <c>T[]</c>,
    /// <c>IEnumerable&lt;T&gt;</c>, <c>IReadOnlyList&lt;T&gt;</c>, <c>IReadOnlyCollection&lt;T&gt;</c>,
    /// <c>IList&lt;T&gt;</c>, <c>ICollection&lt;T&gt;</c>, <c>IAsyncEnumerable&lt;T&gt;</c>).
    /// The element <c>JsonTypeInfo</c> must be supplied by a separate registered context — typically
    /// a hand-written <see cref="global::System.Text.Json.Serialization.JsonSerializerContext"/> with
    /// <c>[JsonSerializable(typeof(T))]</c>.
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class
        | global::System.AttributeTargets.Struct
        | global::System.AttributeTargets.Interface
        | global::System.AttributeTargets.Assembly,
        AllowMultiple = true,
        Inherited = false)]
    internal sealed class ShinyJsonIncludeAttribute : global::System.Attribute
    {
        public ShinyJsonIncludeAttribute() { }
        public ShinyJsonIncludeAttribute(global::System.Type type) { Type = type; }
        public global::System.Type? Type { get; }
    }
}
""";

    static readonly DiagnosticDescriptor OpenGenericRule = new(
        id: "SJSON002",
        title: "ShinyJsonInclude does not support unbound generic types",
        messageFormat: "Type '{0}' is an unbound generic and cannot be included; use a closed constructed type instead",
        category: "Shiny.Extensions.Serialization",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    static readonly DiagnosticDescriptor MissingJsonSerializableRule = new(
        id: "SJSON003",
        title: "Type marked with [ShinyJsonInclude] is not declared in any JsonSerializerContext",
        messageFormat: "Type '{0}' is marked with [ShinyJsonInclude] but no JsonSerializerContext in this compilation declares [JsonSerializable(typeof({0}))]. Generated collection wrappers will return null at runtime and serialization will throw — add [JsonSerializable(typeof({0}))] to a registered JsonSerializerContext.",
        category: "Shiny.Extensions.Serialization",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true
    );


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("ShinyJsonAttributes.g.cs", AttributesSource));

        // Hosts: [ShinyJsonContext] on user-declared JsonSerializerContext partials.
        var hosts = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ContextAttributeMetadataName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => ExtractHost(ctx)
            )
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value);

        // Type-level [ShinyJsonInclude].
        var typeIncludes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                IncludeAttributeMetadataName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => ExtractTypeInclude(ctx)
            )
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value);

        // Assembly-level [assembly: ShinyJsonInclude(typeof(T))].
        var asmIncludes = context.CompilationProvider
            .SelectMany(static (compilation, _) => ExtractAssemblyIncludes(compilation));

        // Every type covered by [JsonSerializable(typeof(T))] in this compilation. Used for SJSON003.
        var serializableTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                JsonSerializableAttributeMetadataName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => ExtractSerializableTypes(ctx)
            )
            .SelectMany(static (arr, _) => arr);

        var asmName = context.CompilationProvider
            .Select(static (c, _) => Sanitize(c.AssemblyName ?? "Assembly"));

        var hostCollected = hosts.Collect().Combine(asmName);
        context.RegisterSourceOutput(hostCollected, static (spc, data) =>
        {
            var (hostSymbols, asm) = data;
            if (hostSymbols.IsDefaultOrEmpty)
                return;

            EmitContextRegistrations(spc, asm, hostSymbols);
        });

        var includesCollected = typeIncludes.Collect()
            .Combine(asmIncludes.Collect())
            .Combine(serializableTypes.Collect())
            .Combine(asmName);

        context.RegisterSourceOutput(includesCollected, static (spc, data) =>
        {
            var (((typeT, asmT), serializable), asm) = data;
            var serializableSet = new HashSet<string>(serializable, StringComparer.Ordinal);

            var all = typeT.Concat(asmT)
                .GroupBy(t => t.FullyQualifiedName, StringComparer.Ordinal)
                .Select(g => g.First())
                .ToImmutableArray();

            foreach (var t in all)
            {
                if (t.Diagnostic is not null)
                {
                    spc.ReportDiagnostic(t.Diagnostic);
                    continue;
                }

                if (!serializableSet.Contains(t.FullyQualifiedName))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        MissingJsonSerializableRule,
                        t.Location,
                        t.FullyQualifiedName
                    ));
                }
            }

            var valid = all.Where(t => t.Diagnostic is null).ToImmutableArray();
            if (valid.Length == 0)
                return;

            EmitCollectionResolver(spc, asm, valid);
        });
    }


    static HostInfo? ExtractHost(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var fqn = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return new HostInfo(fqn);
    }


    static IncludeInfo? ExtractTypeInclude(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        return MakeInclude(typeSymbol, ctx.TargetNode.GetLocation());
    }


    static ImmutableArray<IncludeInfo> ExtractAssemblyIncludes(Compilation compilation)
    {
        var attrType = compilation.GetTypeByMetadataName(IncludeAttributeMetadataName);
        if (attrType is null)
            return ImmutableArray<IncludeInfo>.Empty;

        var builder = ImmutableArray.CreateBuilder<IncludeInfo>();
        foreach (var attr in compilation.Assembly.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attrType))
                continue;

            if (attr.ConstructorArguments.Length == 0)
                continue;

            if (attr.ConstructorArguments[0].Value is not INamedTypeSymbol typeSymbol)
                continue;

            var location = attr.ApplicationSyntaxReference?.GetSyntax().GetLocation();
            var info = MakeInclude(typeSymbol, location);
            if (info is not null)
                builder.Add(info.Value);
        }
        return builder.ToImmutable();
    }


    static ImmutableArray<string> ExtractSerializableTypes(GeneratorAttributeSyntaxContext ctx)
    {
        var builder = ImmutableArray.CreateBuilder<string>();
        foreach (var attr in ctx.Attributes)
        {
            if (attr.ConstructorArguments.Length == 0)
                continue;
            if (attr.ConstructorArguments[0].Value is not INamedTypeSymbol typeSymbol)
                continue;
            builder.Add(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }
        return builder.ToImmutable();
    }


    static IncludeInfo? MakeInclude(INamedTypeSymbol typeSymbol, Location? location)
    {
        var fqn = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (typeSymbol.IsUnboundGenericType)
        {
            return new IncludeInfo(
                fqn,
                location,
                Diagnostic.Create(OpenGenericRule, location, typeSymbol.Name)
            );
        }

        return new IncludeInfo(fqn, location, null);
    }


    static void EmitContextRegistrations(SourceProductionContext spc, string asmName, ImmutableArray<HostInfo> hosts)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Shiny.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal static class {asmName}JsonContextRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Init()");
        sb.AppendLine("    {");
        foreach (var h in hosts.GroupBy(h => h.FullyQualifiedName, StringComparer.Ordinal).Select(g => g.First()))
            sb.AppendLine($"        global::Shiny.Json.AddContext({h.FullyQualifiedName}.Default);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{asmName}JsonContextRegistrations.g.cs", sb.ToString());
    }


    static void EmitCollectionResolver(SourceProductionContext spc, string asmName, ImmutableArray<IncludeInfo> targets)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine();
        sb.AppendLine("namespace Shiny.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal sealed class {asmName}CollectionResolver : IJsonTypeInfoResolver");
        sb.AppendLine("{");
        sb.AppendLine($"    internal static readonly {asmName}CollectionResolver Instance = new();");
        sb.AppendLine();
        sb.AppendLine("    public JsonTypeInfo? GetTypeInfo(Type type, JsonSerializerOptions options)");
        sb.AppendLine("    {");

        for (int i = 0; i < targets.Length; i++)
        {
            var fqn = targets[i].FullyQualifiedName;
            sb.AppendLine($"        if (type == typeof(global::System.Collections.Generic.List<{fqn}>))");
            sb.AppendLine($"            return CreateList<{fqn}>(options);");
            sb.AppendLine($"        if (type == typeof({fqn}[]))");
            sb.AppendLine($"            return CreateArray<{fqn}>(options);");
            sb.AppendLine($"        if (type == typeof(global::System.Collections.Generic.IEnumerable<{fqn}>))");
            sb.AppendLine($"            return CreateEnumerable<{fqn}>(options);");
            sb.AppendLine($"        if (type == typeof(global::System.Collections.Generic.IReadOnlyList<{fqn}>))");
            sb.AppendLine($"            return CreateReadOnlyList<{fqn}>(options);");
            sb.AppendLine($"        if (type == typeof(global::System.Collections.Generic.IReadOnlyCollection<{fqn}>))");
            sb.AppendLine($"            return CreateReadOnlyCollection<{fqn}>(options);");
            sb.AppendLine($"        if (type == typeof(global::System.Collections.Generic.IList<{fqn}>))");
            sb.AppendLine($"            return CreateIList<{fqn}>(options);");
            sb.AppendLine($"        if (type == typeof(global::System.Collections.Generic.ICollection<{fqn}>))");
            sb.AppendLine($"            return CreateICollection<{fqn}>(options);");
            sb.AppendLine($"        if (type == typeof(global::System.Collections.Generic.IAsyncEnumerable<{fqn}>))");
            sb.AppendLine($"            return CreateAsyncEnumerable<{fqn}>(options);");
        }

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static JsonTypeInfo? CreateList<T>(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var elem = ResolveElement<T>(options);");
        sb.AppendLine("        if (elem is null) return null;");
        sb.AppendLine("        return JsonMetadataServices.CreateListInfo<global::System.Collections.Generic.List<T>, T>(");
        sb.AppendLine("            options,");
        sb.AppendLine("            new JsonCollectionInfoValues<global::System.Collections.Generic.List<T>>");
        sb.AppendLine("            {");
        sb.AppendLine("                ObjectCreator = static () => new global::System.Collections.Generic.List<T>(),");
        sb.AppendLine("                ElementInfo = elem");
        sb.AppendLine("            });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static JsonTypeInfo? CreateArray<T>(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var elem = ResolveElement<T>(options);");
        sb.AppendLine("        if (elem is null) return null;");
        sb.AppendLine("        return JsonMetadataServices.CreateArrayInfo<T>(");
        sb.AppendLine("            options,");
        sb.AppendLine("            new JsonCollectionInfoValues<T[]>");
        sb.AppendLine("            {");
        sb.AppendLine("                ElementInfo = elem");
        sb.AppendLine("            });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static JsonTypeInfo? CreateEnumerable<T>(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var elem = ResolveElement<T>(options);");
        sb.AppendLine("        if (elem is null) return null;");
        sb.AppendLine("        return JsonMetadataServices.CreateIEnumerableInfo<global::System.Collections.Generic.IEnumerable<T>, T>(");
        sb.AppendLine("            options,");
        sb.AppendLine("            new JsonCollectionInfoValues<global::System.Collections.Generic.IEnumerable<T>>");
        sb.AppendLine("            {");
        sb.AppendLine("                ElementInfo = elem");
        sb.AppendLine("            });");
        sb.AppendLine("    }");
        sb.AppendLine();
        // JsonMetadataServices has no factory for IReadOnlyList/IReadOnlyCollection — these
        // go through CreateValueInfo + a generated converter that round-trips via List<T>.
        sb.AppendLine("    static JsonTypeInfo? CreateReadOnlyList<T>(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var elem = ResolveElement<T>(options);");
        sb.AppendLine("        if (elem is null) return null;");
        sb.AppendLine("        return JsonMetadataServices.CreateValueInfo<global::System.Collections.Generic.IReadOnlyList<T>>(options, new ReadOnlyListConverter<T>(elem));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static JsonTypeInfo? CreateReadOnlyCollection<T>(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var elem = ResolveElement<T>(options);");
        sb.AppendLine("        if (elem is null) return null;");
        sb.AppendLine("        return JsonMetadataServices.CreateValueInfo<global::System.Collections.Generic.IReadOnlyCollection<T>>(options, new ReadOnlyCollectionConverter<T>(elem));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static JsonTypeInfo? CreateIList<T>(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var elem = ResolveElement<T>(options);");
        sb.AppendLine("        if (elem is null) return null;");
        sb.AppendLine("        return JsonMetadataServices.CreateIListInfo<global::System.Collections.Generic.IList<T>, T>(");
        sb.AppendLine("            options,");
        sb.AppendLine("            new JsonCollectionInfoValues<global::System.Collections.Generic.IList<T>>");
        sb.AppendLine("            {");
        sb.AppendLine("                ObjectCreator = static () => new global::System.Collections.Generic.List<T>(),");
        sb.AppendLine("                ElementInfo = elem");
        sb.AppendLine("            });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static JsonTypeInfo? CreateICollection<T>(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var elem = ResolveElement<T>(options);");
        sb.AppendLine("        if (elem is null) return null;");
        sb.AppendLine("        return JsonMetadataServices.CreateICollectionInfo<global::System.Collections.Generic.ICollection<T>, T>(");
        sb.AppendLine("            options,");
        sb.AppendLine("            new JsonCollectionInfoValues<global::System.Collections.Generic.ICollection<T>>");
        sb.AppendLine("            {");
        sb.AppendLine("                ObjectCreator = static () => new global::System.Collections.Generic.List<T>(),");
        sb.AppendLine("                ElementInfo = elem");
        sb.AppendLine("            });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static JsonTypeInfo? CreateAsyncEnumerable<T>(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        var elem = ResolveElement<T>(options);");
        sb.AppendLine("        if (elem is null) return null;");
        sb.AppendLine("        return JsonMetadataServices.CreateIAsyncEnumerableInfo<global::System.Collections.Generic.IAsyncEnumerable<T>, T>(");
        sb.AppendLine("            options,");
        sb.AppendLine("            new JsonCollectionInfoValues<global::System.Collections.Generic.IAsyncEnumerable<T>>");
        sb.AppendLine("            {");
        sb.AppendLine("                ElementInfo = elem");
        sb.AppendLine("            });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static JsonTypeInfo<T>? ResolveElement<T>(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        try { return options.GetTypeInfo(typeof(T)) as JsonTypeInfo<T>; }");
        sb.AppendLine("        catch (System.InvalidOperationException) { return null; }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    sealed class ReadOnlyListConverter<T> : global::System.Text.Json.Serialization.JsonConverter<global::System.Collections.Generic.IReadOnlyList<T>>");
        sb.AppendLine("    {");
        sb.AppendLine("        readonly JsonTypeInfo<T> elementInfo;");
        sb.AppendLine("        public ReadOnlyListConverter(JsonTypeInfo<T> elementInfo) => this.elementInfo = elementInfo;");
        sb.AppendLine();
        sb.AppendLine("        public override global::System.Collections.Generic.IReadOnlyList<T>? Read(ref global::System.Text.Json.Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null) return null;");
        sb.AppendLine("            if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartArray) throw new global::System.Text.Json.JsonException();");
        sb.AppendLine("            var list = new global::System.Collections.Generic.List<T>();");
        sb.AppendLine("            while (reader.Read())");
        sb.AppendLine("            {");
        sb.AppendLine("                if (reader.TokenType == global::System.Text.Json.JsonTokenType.EndArray) return list;");
        sb.AppendLine("                list.Add(global::System.Text.Json.JsonSerializer.Deserialize(ref reader, this.elementInfo)!);");
        sb.AppendLine("            }");
        sb.AppendLine("            throw new global::System.Text.Json.JsonException();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, global::System.Collections.Generic.IReadOnlyList<T> value, JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteStartArray();");
        sb.AppendLine("            for (int i = 0; i < value.Count; i++)");
        sb.AppendLine("                global::System.Text.Json.JsonSerializer.Serialize(writer, value[i], this.elementInfo);");
        sb.AppendLine("            writer.WriteEndArray();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    sealed class ReadOnlyCollectionConverter<T> : global::System.Text.Json.Serialization.JsonConverter<global::System.Collections.Generic.IReadOnlyCollection<T>>");
        sb.AppendLine("    {");
        sb.AppendLine("        readonly JsonTypeInfo<T> elementInfo;");
        sb.AppendLine("        public ReadOnlyCollectionConverter(JsonTypeInfo<T> elementInfo) => this.elementInfo = elementInfo;");
        sb.AppendLine();
        sb.AppendLine("        public override global::System.Collections.Generic.IReadOnlyCollection<T>? Read(ref global::System.Text.Json.Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null) return null;");
        sb.AppendLine("            if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartArray) throw new global::System.Text.Json.JsonException();");
        sb.AppendLine("            var list = new global::System.Collections.Generic.List<T>();");
        sb.AppendLine("            while (reader.Read())");
        sb.AppendLine("            {");
        sb.AppendLine("                if (reader.TokenType == global::System.Text.Json.JsonTokenType.EndArray) return list;");
        sb.AppendLine("                list.Add(global::System.Text.Json.JsonSerializer.Deserialize(ref reader, this.elementInfo)!);");
        sb.AppendLine("            }");
        sb.AppendLine("            throw new global::System.Text.Json.JsonException();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, global::System.Collections.Generic.IReadOnlyCollection<T> value, JsonSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteStartArray();");
        sb.AppendLine("            foreach (var item in value)");
        sb.AppendLine("                global::System.Text.Json.JsonSerializer.Serialize(writer, item, this.elementInfo);");
        sb.AppendLine("            writer.WriteEndArray();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"internal static class {asmName}CollectionResolverInit");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine($"    internal static void Init() => global::Shiny.Json.AddResolver({asmName}CollectionResolver.Instance);");
        sb.AppendLine("}");

        spc.AddSource($"{asmName}CollectionResolver.g.cs", sb.ToString());
    }


    static string Sanitize(string name)
    {
        var sb = new StringBuilder(name.Length);
        for (int i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (char.IsLetterOrDigit(c))
                sb.Append(c);
            else if (c == '.' || c == '_' || c == '-' || c == '+')
                sb.Append('_');
        }
        if (sb.Length == 0 || char.IsDigit(sb[0]))
            sb.Insert(0, '_');
        return sb.ToString();
    }


    readonly struct HostInfo : IEquatable<HostInfo>
    {
        public HostInfo(string fullyQualifiedName) { FullyQualifiedName = fullyQualifiedName; }
        public string FullyQualifiedName { get; }
        public bool Equals(HostInfo other) => FullyQualifiedName == other.FullyQualifiedName;
        public override bool Equals(object? obj) => obj is HostInfo h && Equals(h);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(FullyQualifiedName);
    }


    readonly struct IncludeInfo : IEquatable<IncludeInfo>
    {
        public IncludeInfo(string fullyQualifiedName, Location? location, Diagnostic? diagnostic)
        {
            FullyQualifiedName = fullyQualifiedName;
            Location = location;
            Diagnostic = diagnostic;
        }
        public string FullyQualifiedName { get; }
        public Location? Location { get; }
        public Diagnostic? Diagnostic { get; }

        // Location intentionally excluded from equality so incremental caching ignores file-position drift.
        public bool Equals(IncludeInfo other) => FullyQualifiedName == other.FullyQualifiedName && ReferenceEquals(Diagnostic, other.Diagnostic);
        public override bool Equals(object? obj) => obj is IncludeInfo i && Equals(i);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(FullyQualifiedName);
    }
}
