//HintName: WebModuleExtensions.g.cs
// <auto-generated />
using global::Microsoft.AspNetCore.Builder;
using global::Microsoft.Extensions.DependencyInjection;


namespace Shiny;


public static class WebModuleExtensions
{
    public static WebApplicationBuilder AddAllWebModules(this WebApplicationBuilder builder)
    {
        return builder;
    }

    public static WebApplicationBuilder AddWebModules(this WebApplicationBuilder builder, params global::Shiny.IWebModule[] modules)
    {
        foreach (var module in modules)
        {
            module.Add(builder);
            builder.Services.AddTransient<global::Shiny.IWebModule>(_ => module);
        }
        return builder;
    }

    public static WebApplication UseWebModules(this WebApplication app)
    {
        var modules = app.Services.GetServices<global::Shiny.IWebModule>();
        foreach (var module in modules)
        {
            module.Use(app);
        }
        return app;
    }
}
